name: Build APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v3
        with:
          name: taxi-kirkuk-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
